// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zphcynhpgruxwibonwcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwaGN5bmhwZ3J1eHdpYm9ud2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2OTI2NzksImV4cCI6MjA1NDI2ODY3OX0.8UE4A-TOKKYsXSUTPOU3fIPFUw03Hxi1crWey0_m_Jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);